spring:
  security:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    oauth2:
      client:
        registration:
          google:
            client-id: 165337007718-a697qijffj4ibjnlfkbb8usbqt4poq5c.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  port: 8082